"""Secret_Scan tests — scripts/scan-secrets.sh driven through subprocess.

The scan takes its scope from ``git ls-files``, so every fixture here is a real
throwaway git repository: ``git init`` plus ``git add``. Anything the fixture
does not stage is out of scope by construction, which is the property the design
relies on for node_modules/, cdk.out/ and config/accounts.json.

No 12-digit literal appears in this source. Identifiers are assembled at runtime
by ``fake_account_id`` / ``placeholder_id`` from conftest (Requirement 6.5).

Requirements: 6.5, 6.6
"""

from __future__ import annotations

import hashlib
import shutil
import subprocess
from pathlib import Path

import pytest

from .conftest import REPO_ROOT, fake_account_id, placeholder_id

SCAN_SCRIPT = REPO_ROOT / "scripts" / "scan-secrets.sh"
BASELINE_NAME = "scripts/scan-secrets.baseline"
BASH = shutil.which("bash") or "/bin/bash"
GIT = shutil.which("git") or "/usr/bin/git"

# A CloudFormation-generated physical name, assembled at runtime from its parts
# so the committed source carries no live-looking name either: stack, logical id
# plus 8-hex logical-id hash, and the random suffix.
CFN_STACK = "DevSampleStack"
CFN_LOGICAL = "QueueResourcessqssample"
CFN_HASH = "AB12CD34"
CFN_SUFFIX = "Zq7XmT4vB2ke"
CFN_NAME = f"{CFN_STACK}-{CFN_LOGICAL}{CFN_HASH}-{CFN_SUFFIX}"


def baseline(*entries: tuple[str, str]) -> str:
    """Render a baseline file body from (path glob, accepted value) pairs.

    The digest is computed here the same way the script and the baseline's own
    instructions compute it: sha256 of the exact value with no trailing newline.
    """
    lines = ["# generated by the test suite"]
    for path, value in entries:
        digest = hashlib.sha256(value.encode()).hexdigest()
        lines.append(f"{path} | {digest} | accepted by a test")
    return "\n".join(lines) + "\n"


def make_git_repo(root: Path, files: dict[str, str], stage: bool = True) -> Path:
    """Create a git repo at ``root`` holding ``files``, staging them by default.

    The scan resolves the repository root from its own location, so the script is
    copied to ``<root>/scripts/scan-secrets.sh`` exactly as it sits in this
    repository.
    """
    root.mkdir(parents=True, exist_ok=True)
    (root / "scripts").mkdir(exist_ok=True)
    shutil.copy2(SCAN_SCRIPT, root / "scripts" / "scan-secrets.sh")

    for relative, content in files.items():
        target = root / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        if isinstance(content, bytes):
            target.write_bytes(content)
        else:
            target.write_text(content)

    subprocess.run([GIT, "init", "--quiet"], cwd=root, check=True, capture_output=True)  # nosec B603  # test harness runs a repo script with a static argv  # nosemgrep: python.lang.security.audit.dangerous-subprocess-use-audit
    if stage:
        subprocess.run(  # nosec B603  # test harness runs a repo script with a static argv  # nosemgrep: python.lang.security.audit.dangerous-subprocess-use-audit
            [GIT, "add", "--", "scripts/scan-secrets.sh", *files],
            cwd=root,
            check=True,
            capture_output=True,
        )
    else:
        subprocess.run(  # nosec B603  # test harness runs a repo script with a static argv  # nosemgrep: python.lang.security.audit.dangerous-subprocess-use-audit
            [GIT, "add", "--", "scripts/scan-secrets.sh"],
            cwd=root,
            check=True,
            capture_output=True,
        )
    return root


def run_scan(root: Path) -> subprocess.CompletedProcess:
    return subprocess.run(  # nosec B603  # test harness runs a repo script with a static argv  # nosemgrep: python.lang.security.audit.dangerous-subprocess-use-audit
        [BASH, str(root / "scripts" / "scan-secrets.sh")],
        cwd=root,
        capture_output=True,
        text=True,
        timeout=120,
    )


def findings(result: subprocess.CompletedProcess) -> list[tuple[str, str, str]]:
    """Parse the account-identifier file:line:value lines out of stdout."""
    return [f for f in all_findings(result) if f[2].isdigit()]


def all_findings(result: subprocess.CompletedProcess) -> list[tuple[str, str, str]]:
    """Parse every file:line:value line, whatever match class produced it."""
    parsed = []
    for line in result.stdout.splitlines():
        parts = line.split(":")
        if len(parts) == 3 and parts[1].isdigit():
            parsed.append((parts[0], parts[1], parts[2]))
    return parsed


@pytest.fixture
def git_repo(tmp_path: Path):
    counter = {"n": 0}

    def _make(files: dict[str, str], stage: bool = True) -> Path:
        counter["n"] += 1
        return make_git_repo(tmp_path / f"case{counter['n']}", files, stage=stage)

    return _make


class TestNonPlaceholderIdentifiers:
    """Requirement 6.5 — a real identifier fails, naming file and line."""

    def test_non_allowlisted_id_fails_with_file_line_value(self, git_repo) -> None:
        leaked = fake_account_id(424242)
        root = git_repo(
            {
                "workload/lib/stack.ts": (
                    "const other = 'nothing here';\n"
                    f"const account = '{leaked}';\n"
                ),
            }
        )

        result = run_scan(root)

        assert result.returncode != 0
        assert findings(result) == [("workload/lib/stack.ts", "2", leaked)]

    def test_every_finding_is_reported_not_just_the_first(self, git_repo) -> None:
        first, second = fake_account_id(424242), fake_account_id(777777)
        root = git_repo(
            {
                "a.md": f"account {first}\n",
                "b.md": f"line one\naccount {second}\n",
            }
        )

        result = run_scan(root)

        assert result.returncode != 0
        assert findings(result) == [
            ("a.md", "1", first),
            ("b.md", "2", second),
        ]

    def test_untracked_file_is_out_of_scope(self, git_repo) -> None:
        """Scope is structural: an unstaged file is not scanned at all."""
        root = git_repo(
            {"config/accounts.json": f'{{"id": "{fake_account_id(424242)}"}}\n'},
            stage=False,
        )

        result = run_scan(root)

        assert result.returncode == 0, result.stdout + result.stderr
        assert findings(result) == []


class TestCanonicalPlaceholders:
    """Requirement 6.5 — the three canonical placeholders are allowed."""

    def test_file_with_only_canonical_placeholders_passes(self, git_repo) -> None:
        be, fe, ops = placeholder_id(1), placeholder_id(2), placeholder_id(3)
        root = git_repo(
            {
                "test/fixture.ts": (
                    f"const beAccount = '{be}';\n"
                    f"const feAccount = '{fe}';\n"
                    f"const opsAccount = '{ops}';\n"
                    f"const roleArn = 'arn:aws:iam::{ops}:role/demo';\n"
                ),
            }
        )

        result = run_scan(root)

        assert result.returncode == 0, result.stdout + result.stderr
        assert findings(result) == []

    def test_off_pattern_placeholder_is_not_allowlisted(self, git_repo) -> None:
        """Only the canonical three pass; the scan has exactly one rule."""
        off_pattern = fake_account_id(0)
        root = git_repo({"scripts/demo.sh": f'ACCOUNT="{off_pattern}"\n'})

        result = run_scan(root)

        assert result.returncode != 0
        assert findings(result) == [("scripts/demo.sh", "1", off_pattern)]


class TestBaseline:
    """Requirement 6.6 — the baseline mechanism, scoped to path and value.

    ``docs/deployment.md`` used to be a whole-file exclusion (decision D3),
    which put the scan's blind spot in the largest and fastest-growing file in
    the repository. D3 was narrowed to per-value baseline entries and has since
    been **reversed on security-standards grounds**: the run log's identifiers
    were replaced with placeholders and the shipped
    ``scripts/scan-secrets.baseline`` is empty, so nothing in the repository is
    exempt. These cases therefore exercise the mechanism against fixture
    baselines only — the shipped one accepts nothing, which
    ``test_shipped_baseline_has_no_entries`` pins down.
    """

    RUN_LOG = "docs/deployment.md"

    def test_shipped_baseline_has_no_entries(self) -> None:
        """D3 reversed: the repository's own baseline accepts nothing."""
        shipped = REPO_ROOT / "scripts" / "scan-secrets.baseline"
        entries = [
            line
            for line in shipped.read_text().splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        ]

        assert entries == [], (
            "scripts/scan-secrets.baseline is intentionally empty — no file or "
            f"value in this repository is exempt from the gate: {entries}"
        )

    def test_run_log_id_without_a_baseline_entry_fails(self, git_repo) -> None:
        """No path is exempt by name: the run log is scanned like anything else."""
        historical = fake_account_id(424242)
        root = git_repo({self.RUN_LOG: f"Deployed to {historical}\n"})

        result = run_scan(root)

        assert result.returncode != 0
        assert findings(result) == [(self.RUN_LOG, "1", historical)]

    def test_baselined_id_passes_without_editing_the_file(self, git_repo) -> None:
        historical = fake_account_id(424242)
        root = git_repo(
            {
                self.RUN_LOG: f"Deployed to {historical}\n",
                BASELINE_NAME: baseline((self.RUN_LOG, historical)),
            }
        )

        result = run_scan(root)

        assert result.returncode == 0, result.stdout + result.stderr
        assert all_findings(result) == []

    def test_new_id_in_a_baselined_file_still_fails(self, git_repo) -> None:
        """The point of the change: acceptance is per value, not per file."""
        historical, added = fake_account_id(424242), fake_account_id(777777)
        root = git_repo(
            {
                self.RUN_LOG: f"Deployed to {historical}\nLater: {added}\n",
                BASELINE_NAME: baseline((self.RUN_LOG, historical)),
            }
        )

        result = run_scan(root)

        assert result.returncode != 0
        assert findings(result) == [(self.RUN_LOG, "2", added)]

    def test_acceptance_does_not_leak_into_another_path(self, git_repo) -> None:
        """A value accepted in the run log is still a leak in source."""
        historical = fake_account_id(424242)
        root = git_repo(
            {
                self.RUN_LOG: f"Deployed to {historical}\n",
                "workload/lib/stack.ts": f"const account = '{historical}';\n",
                BASELINE_NAME: baseline((self.RUN_LOG, historical)),
            }
        )

        result = run_scan(root)

        assert result.returncode != 0
        assert findings(result) == [("workload/lib/stack.ts", "1", historical)]

    def test_malformed_baseline_line_is_an_environment_error(self, git_repo) -> None:
        """A baseline that cannot be parsed must not silently accept nothing."""
        root = git_repo(
            {
                self.RUN_LOG: f"Deployed to {fake_account_id(424242)}\n",
                BASELINE_NAME: "docs/deployment.md | not-a-digest | why\n",
            }
        )

        result = run_scan(root)

        assert result.returncode == 2
        assert "sha256" in result.stderr

    def test_baseline_digests_do_not_fail_the_scan(self, git_repo) -> None:
        """A sha256 digest carries a 12-digit run often enough to matter.

        Roughly one digest in five contains twelve consecutive digits, so an
        unmasked baseline would fail the gate it feeds. The digest token is
        masked; the seeds below are chosen so at least one entry hits the case.
        """
        entries = [(self.RUN_LOG, fake_account_id(seed)) for seed in range(1, 40)]
        digests = [hashlib.sha256(v.encode()).hexdigest() for _, v in entries]
        assert any(
            any(d[i : i + 12].isdigit() for i in range(len(d) - 11)) for d in digests
        ), "fixture no longer exercises the digit-run case"

        root = git_repo(
            {
                self.RUN_LOG: "".join(f"account {v}\n" for _, v in entries),
                BASELINE_NAME: baseline(*entries),
            }
        )

        result = run_scan(root)

        assert result.returncode == 0, result.stdout + result.stderr
        assert all_findings(result) == []


class TestGeneratedResourceNames:
    """A resource name carrying a CloudFormation-generated suffix is a finding.

    It is a live identifier of one deployment: not reproducible, not a
    placeholder, and not twelve digits, so the account pattern never saw it.
    """

    def test_generated_name_fails_with_file_line_value(self, git_repo) -> None:
        root = git_repo({"docs/notes.md": f"The live queue is `{CFN_NAME}`.\n"})

        result = run_scan(root)

        assert result.returncode != 0
        assert all_findings(result) == [("docs/notes.md", "1", CFN_NAME)]

    def test_baselined_generated_name_passes(self, git_repo) -> None:
        root = git_repo(
            {
                "docs/deployment.md": f"Run log: the queue was `{CFN_NAME}`.\n",
                BASELINE_NAME: baseline(("docs/deployment.md", CFN_NAME)),
            }
        )

        result = run_scan(root)

        assert result.returncode == 0, result.stdout + result.stderr
        assert all_findings(result) == []

    @pytest.mark.parametrize(
        "text",
        [
            "See [accounts and prerequisites](#accounts-and-prerequisites).",
            "Skill `checkout-latency-investigation` is active.",
            "Alarm `aiops-poc-be-slo-search-latency-p99` fired.",
            "Cluster `PetsiteECS-cluster`, service `petsearch-java`.",
            "Investigation `a1b2c3d4-e5f6-4a7b-8c9d-e0f1a2b3c4d5` completed.",
            "Experiment template `EXTsampleAbc1Xyz` stop-task-ALL.",
            "Shape: `<StackName>-<LogicalId><Hash>-<Suffix>`.",
            "Fixed at commit `df7d233` on branch `main`.",
        ],
    )
    def test_documented_shapes_and_names_do_not_trip_the_rule(
        self, git_repo, text: str
    ) -> None:
        """The repo documents resource-name shapes; noise here would kill the gate."""
        root = git_repo({"docs/notes.md": text + "\n"})

        result = run_scan(root)

        assert result.returncode == 0, result.stdout + result.stderr
        assert all_findings(result) == []


class TestStructuralScope:
    """Scope comes from ``git ls-files``, not from a pattern list."""

    def test_untracked_task_metadata_is_out_of_scope(self, git_repo) -> None:
        """Kiro spec metadata is ignored, so its epoch timestamps never reach the scan.

        An epoch-millisecond timestamp is shape-identical to an account ID, so
        the pattern does match it; structural scope, not an exclusion, is what
        keeps the scan quiet, which the paired assertion below makes explicit.
        """
        epoch_ms = str(1784219570 * 1000)  # built at runtime: 13 digits
        root = git_repo(
            {
                ".kiro/specs/centralized-parameters/tasks.meta.json": (
                    '{"updatedAt": ' + epoch_ms + "}\n"
                ),
            },
            stage=False,
        )

        result = run_scan(root)

        assert result.returncode == 0, result.stdout + result.stderr
        assert findings(result) == []

    def test_same_epoch_timestamp_in_a_tracked_file_does_trigger(
        self, git_repo
    ) -> None:
        """No path is exempt by shape: a tracked 13-digit run is reported."""
        epoch_ms = str(1784219570 * 1000)  # built at runtime: 13 digits
        root = git_repo({"notes/timing.json": '{"updatedAt": ' + epoch_ms + "}\n"})

        result = run_scan(root)

        assert result.returncode != 0
        assert findings(result) == [("notes/timing.json", "1", epoch_ms[:12])]

    def test_tracked_task_metadata_is_still_scanned(self, git_repo) -> None:
        """The name carries no exemption — staged, the same file is in scope."""
        leaked = fake_account_id(424242)
        root = git_repo({"tasks.meta.json": f'{{"account": "{leaked}"}}\n'})

        result = run_scan(root)

        assert result.returncode != 0
        assert findings(result) == [("tasks.meta.json", "1", leaked)]


class TestNonAccountTokens:
    """Requirement 6.6 — a masked token is skipped without excluding the file.

    The live case is the synth-time PrivateLink placeholder in
    ``workload/frontend/lib/frontend-stack.ts``: an all-zero vpce-svc- suffix
    whose leading twelve digits match the account-ID pattern. The mask is
    token-scoped rather than path-scoped precisely so that production source
    keeps being scanned, which the paired assertion below pins down.
    """

    FRONTEND_STACK = "workload/frontend/lib/frontend-stack.ts"

    def _placeholder_line(self) -> str:
        # 17-character all-zero suffix, assembled at runtime.
        return (
            "      privatelinkServiceName = "
            f"'com.amazonaws.vpce.placeholder.vpce-svc-{'0' * 17}';\n"
        )

    def test_vpce_service_placeholder_passes(self, git_repo) -> None:
        root = git_repo({self.FRONTEND_STACK: self._placeholder_line()})

        result = run_scan(root)

        assert result.returncode == 0, result.stdout + result.stderr
        assert findings(result) == []

    def test_real_id_in_the_same_file_still_fails(self, git_repo) -> None:
        """The mask is not a file exclusion: the rest of the file stays in scope."""
        leaked = fake_account_id(424242)
        root = git_repo(
            {
                self.FRONTEND_STACK: (
                    self._placeholder_line() + f"      const account = '{leaked}';\n"
                ),
            }
        )

        result = run_scan(root)

        assert result.returncode != 0
        assert findings(result) == [(self.FRONTEND_STACK, "2", leaked)]

    def test_masking_does_not_shift_reported_line_numbers(self, git_repo) -> None:
        leaked = fake_account_id(777777)
        root = git_repo(
            {
                self.FRONTEND_STACK: (
                    "// header\n"
                    + self._placeholder_line()
                    + "// spacer\n"
                    + f"const account = '{leaked}';\n"
                ),
            }
        )

        result = run_scan(root)

        assert result.returncode != 0
        assert findings(result) == [(self.FRONTEND_STACK, "4", leaked)]


class TestBinaryFiles:
    """Binary files are skipped rather than reported as noise."""

    def test_binary_file_is_skipped(self, git_repo) -> None:
        leaked = fake_account_id(424242)
        root = git_repo({"assets/blob.bin": "\x00\x01" + leaked + "\x00"})

        result = run_scan(root)

        assert result.returncode == 0, result.stdout + result.stderr
        assert findings(result) == []
